pbvs_controller:
  ros__parameters:
    move_group_name: "Rizon4s-063387_arm"
    base_frame: "Rizon4s-063387_base_link"  # Matches your live /tf topic
    ee_frame: "Rizon4s-063387_flange"        # Your physical flange link
    
    # --- State Machine Configuration ---
    target_timeout_sec: 0.5
    continue_to_last_known_target: false     # Safely tracks the last resolved pose if occluded
    
    # --- Tuning Gains & Speed Safety Caps ---
    gain_translation: 60.0                 #
    gain_rotation: 35.0                      
    max_translation_vel: 5.0           
    max_rotation_vel: 5.0                   
    desired_standoff: 0.4                  # The distance to maintain from the target (in meters)
    
    deadband_translation: 0.006             
    deadband_rotation: 0.01                


    smoothing_alpha: 1.0                  # lower = smoother, but more laggy. Valid range [0.0:1.0]
    publish_frequency: 250.0                # Control loop frequency in Hz (default is 100Hz)


    # Debugging purpose(dont)
    sign_x: 1
    sign_y: 1
    sign_z: 1

    sign_rx: -1
    sign_ry: -1
    sign_rz: 1

    offset_x: -0.1
    offset_y: -0.1